def play_voice():
    text_=t1.get(1.0,END)
    text_1=Translator()
    trans_text=text_1.translate(text_,src=combo1.get(),dest=combo2.get())
    trans_text=trans_text.text
    if(combo2.get()=="amharic"):
        lang="am"
    elif(combo2.get()=="arabic"):
        lang="ar"
    elif(combo2.get()=="basque"):
        lang="eu"
    elif(combo2.get()=="bengali"):
        lang="bn"
    elif(combo2.get()=="english"):
        lang="en"
    elif(combo2.get()=="portuguese"):
        lang="pt"
    elif(combo2.get()=="bulgarian"):
        lang="bg"
    elif(combo2.get()=="catalan"):
        lang="ca"
    elif(combo2.get()=="cherokee"):
        lang="chr"
    elif(combo2.get()=="croatian"):
        lang="hr"
    elif(combo2.get()=="czech"):
        lang="cs"
    elif(combo2.get()=="danish"):
        lang="da"
    elif(combo2.get()=="dutch"):
        lang="nl"
    elif(combo2.get()=="estonian"):
        lang="et"
    elif(combo2.get()=="filipino"):
        lang="fil"
    elif(combo2.get()=="finnish"):
        lang="fi"
    elif(combo2.get()=="french"):
        lang="fr"
    elif(combo2.get()=="german"):
        lang="de"
    elif(combo2.get()=="greek"):
        lang="el"
    elif(combo2.get()=="gujarati"):
        lang="gu"
    elif(combo2.get()=="hebrew"):
        lang="iw"
    elif(combo2.get()=="hindi"):
        lang="hi"
    elif(combo2.get()=="hungarian"):
        lang="hu"
    elif(combo2.get()=="icelandic"):
        lang="is"
    elif(combo2.get()=="indonesian"):
        lang="id"
    elif(combo2.get()=="italian"):
        lang="it"
    elif(combo2.get()=="japanese"):
        lang="ja"
    elif(combo2.get()=="kannada"):
        lang="kn"
    elif(combo2.get()=="korean"):
        lang="ko"
    elif(combo2.get()=="latvian"):
        lang="lv"
    elif(combo2.get()=="lithuanian"):
        lang="lt"
    elif(combo2.get()=="malay"):
        lang="ms"
    elif(combo2.get()=="malayalam"):
        lang="ml"
    elif(combo2.get()=="marathi"):
        lang="mr"
    elif(combo2.get()=="norwegian"):
        lang="no"
    elif(combo2.get()=="polish"):
        lang="pl"
    elif(combo2.get()=="romanian"):
        lang="ro"
    elif(combo2.get()=="russian"):
        lang="ru"
    elif(combo2.get()=="serbian"):
        lang="sr"
    elif(combo2.get()=="slovak"):
        lang="sk"
    elif(combo2.get()=="slovenian"):
        lang="sl"
    elif(combo2.get()=="spanish"):
        lang="es"
    elif(combo2.get()=="swahili"):
        lang="sw"
    elif(combo2.get()=="swedish"):
        lang="sv"
    elif(combo2.get()=="tamil"):
        lang="ta"
    elif(combo2.get()=="telugu"):
        lang="te"
    elif(combo2.get()=="thai"):
        lang="th"
    elif(combo2.get()=="turkish"):
        lang="tr"
    elif(combo2.get()=="urdu"):
        lang="ur"
    elif(combo2.get()=="ukrainian"):
        lang="uk"
    elif(combo2.get()=="vietnamese"):
        lang="vi"
    elif(combo2.get()=="welsh"):
        lang="cy"

    sound=gtts.gTTS(trans_text,lang)
    sound.save("audio.mp3")
    playsound.playsound("audio.mp3")
    os.remove("audio.mp3")